In [137]:
import numpy as np
import pandas as pd

In [138]:
#File Profiling

files = {
    "customers": "customers.csv",
    "products": "products.csv",
    "orders": "orders.csv",
    "order_items": "order_items.csv",
    "payments": "payments.csv",
    "shipments": "shipments.csv",
    "returns": "returns.csv"
}

data = {name: pd.read_csv(path)
        for name, path in files.items()}

for name, df in data.items():
    print(name, df.shape)
    print("=====")
    print(df.isna().sum().sort_values(
        ascending=False).head())
    print("duplicates:", df.duplicated().sum())
    print(df.dtypes)
    print()

customers (5050, 13)
=====
gender          301
loyalty_tier    266
age             150
phone           147
email           107
dtype: int64
duplicates: 50
customer_id         str
first_name          str
last_name           str
gender              str
age             float64
email               str
phone           float64
region_code         str
region_name         str
city                str
barangay            str
signup_date         str
loyalty_tier        str
dtype: object

products (800, 9)
=====
stock_qty       19
product_id       0
product_name     0
category         0
brand            0
dtype: int64
duplicates: 0
product_id          str
product_name        str
brand               str
category            str
unit_cost       float64
unit_price          str
stock_qty       float64
uom                 str
launch_date         str
dtype: object

orders (15075, 8)
=====
discount_pct    758
shipping_fee    474
order_id          0
customer_id       0
order_status      0
dtype: int64
duplicates: 75
order_id               str
customer_id            str
order_datetime         str
order_status           str
sales_channel          str
shipping_method        str
discount_pct       float64
shipping_fee       float64
dtype: object

order_items (37763, 5)
=====
unit_price_at_purchase    2262
order_item_id                0
order_id                     0
product_id                   0
quantity                     0
dtype: int64
duplicates: 262
order_item_id               str
order_id                    str
product_id                  str
quantity                  int64
unit_price_at_purchase      str
dtype: object

payments (15000, 6)
=====
amount_paid       878
payment_id          0
order_id            0
payment_method      0
payment_status      0
dtype: int64
duplicates: 0
payment_id        str
order_id          str
payment_method    str
payment_status    str
payment_date      str
amount_paid       str
dtype: object

shipments (15000, 7)
=====
delivered_date    729
order_id            0
shipment_id         0
courier             0
tracking_no         0
dtype: int64
duplicates: 0
shipment_id        str
order_id           str
courier            str
tracking_no        str
shipment_status    str
ship_date          str
delivered_date     str
dtype: object

returns (1200, 6)
=====
refund_amount    187
refunded_flag    110
order_id           0
return_id          0
reason             0
dtype: int64
duplicates: 0
return_id                  str
order_id                   str
return_request_date        str
reason                     str
refunded_flag              str
refund_amount          float64
dtype: object

In [139]:
#MISSING VALUES - CUSTOMERS

data['customers'].isna().sum().sort_values(ascending=False)

gender          301
loyalty_tier    266
age             150
phone           147
email           107
first_name        0
last_name         0
customer_id       0
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
dtype: int64

In [140]:
customers_clean = data['customers'].copy()

In [408]:
customers_clean['gender'] = customers_clean['gender'].fillna("Unknown")

In [409]:
customers_clean['age'] = customers_clean['age'].fillna(0)

In [410]:
customers_clean['phone'] = customers_clean['phone'].fillna('09100000001')

In [411]:
customers_clean['email'] = customers_clean['email'].fillna('default@gmail.com')

In [412]:
customers_clean['loyalty_tier'] = customers_clean['loyalty_tier'].fillna('Unknown')

In [146]:
customers_clean.isna().sum().sort_values(ascending=False)

customer_id     0
first_name      0
last_name       0
gender          0
age             0
email           0
phone           0
region_code     0
region_name     0
city            0
barangay        0
signup_date     0
loyalty_tier    0
dtype: int64

In [147]:
#MISSING VALUES - ORDERS

data['orders'].isna().sum().sort_values(ascending=False)

discount_pct       758
shipping_fee       474
order_id             0
customer_id          0
order_status         0
order_datetime       0
shipping_method      0
sales_channel        0
dtype: int64

In [148]:
data['orders'][data['orders']['shipping_fee'].isna()]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
10,ORD0000011,CUST001208,2025-07-02 14:16:00,Completed,Mobile App,Pickup,0.235,NaN
14,ORD0000015,CUST000266,2024-01-09 23:45:00,Returned,Mobile App,Express,0.082,NaN
24,ORD0000025,CUST004894,2024-03-07 02:57:00,Cancelled,Mobile App,Standard,0.078,NaN
47,ORD0000048,CUST001493,2024-06-27 15:17:00,Cancelled,Web,Standard,0.101,NaN
74,ORD0000075,CUST004700,2024-11-02 14:57:00,Completed,Web,Pickup,0.095,NaN
...,...,...,...,...,...,...,...,...
14986,ORD0014987,CUST000576,02/08/2024 12:36 AM,Completed,Mobile App,Standard,0.004,NaN
15023,ORD0012522,CUST001778,2024-12-28 14:17:00,Cancelled,Marketplace,Pickup,0.171,NaN
15035,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN
15045,ORD0014321,CUST000723,2025-03-06 23:14:00,Completed,Marketplace,Pickup,0.126,NaN
15051,ORD0010183,CUST004144,02/15/2024 03:03 PM,Pending,Marketplace,Pickup,0.173,NaN

In [149]:
data['orders'][data['orders']['discount_pct'].isna()]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73
11,ORD0000012,CUST004924,2024-09-19 10:13:00,Shipped,Web,Standard,NaN,45.40
17,ORD0000018,CUST002748,02/25/2024 03:07 AM,Shipped,Marketplace,Express,NaN,72.89
31,ORD0000032,CUST001288,2024-07-08 12:19:00,Completed,Mobile App,Pickup,NaN,66.99
42,ORD0000043,CUST001001,2024-08-06 14:56:00,Completed,Marketplace,Standard,NaN,80.03
...,...,...,...,...,...,...,...,...
14931,ORD0014932,CUST003337,06/12/2024 03:44 PM,Shipped,Web,Standard,NaN,59.43
14945,ORD0014946,CUST003418,2024-07-08 15:00:00,Pending,Web,Express,NaN,86.59
14990,ORD0014991,CUST002664,01/09/2026 06:17 PM,Completed,Marketplace,Pickup,NaN,145.84
15002,ORD0009699,CUST002618,2025-05-05 22:11:00,Completed,Web,Pickup,NaN,123.12
15063,ORD0008880,CUST003334,2025-08-20 10:50:00,Completed,Web,Standard,NaN,79.00

In [150]:
data['orders'].loc[
    data['orders']['discount_pct'].notna()
]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69
5,ORD0000006,CUST001560,2024-08-13 18:42:00,Shipped,Mobile App,Pickup,0.089,86.54
...,...,...,...,...,...,...,...,...
15070,ORD0011300,CUST000701,2024-11-17 21:58:00,Cancelled,Marketplace,Express,0.036,75.40
15071,ORD0014948,CUST003808,28-Dec-2025 01:01,Completed,Mobile App,Standard,0.019,142.29
15072,ORD0012066,CUST004052,2025-05-04 06:07:00,Completed,Web,Standard,0.087,107.84
15073,ORD0012132,CUST002798,2025-04-29 21:11:00,Completed,Mobile App,Pickup,0.062,82.12
15074,ORD0013325,CUST001564,03/14/2024 04:48 PM,Completed,Marketplace,Standard,0.117,135.62

In [151]:
data['returns'].isna().sum()

return_id                0
order_id                 0
return_request_date      0
reason                   0
refunded_flag          110
refund_amount          187
dtype: int64

In [152]:
#MISSING VALUES - RETURNS (FLAG)

returns_clean = data['returns'].copy()

In [153]:
returns_clean['refund_amount'].isna().sum()

np.int64(187)

In [154]:
returns_clean['refund_missing'] = returns_clean['refund_amount'].isna()

In [155]:
returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN,True
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False
...,...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74,False
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28,False
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False

In [156]:
returns_clean['refund_amount'].isna().sum()

np.int64(187)

In [157]:
#MISSING VALUES - SHIPMENTS

data['shipments']

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025

In [158]:
shipments_clean = data['shipments'].copy()

In [159]:
shipments_clean[shipments_clean["delivered_date"].isna()][
    ["shipment_id", "shipment_status", "ship_date", "delivered_date"]
]

      shipment_id shipment_status    ship_date delivered_date
24     SHP0000025       Delivered   2024-03-19            NaN
27     SHP0000028       Delivered   2024-03-31            NaN
38     SHP0000039       Delivered  13-Oct-2024            NaN
64     SHP0000065       Delivered   2024-01-19            NaN
71     SHP0000072       Delivered   2025-04-03            NaN
...           ...             ...          ...            ...
14916  SHP0014917       Delivered   2024-03-27            NaN
14958  SHP0014959       Delivered   2026-01-23            NaN
14978  SHP0014979       Delivered   2025-12-16            NaN
14981  SHP0014982      In Transit   2025-06-06            NaN
14994  SHP0014995      In Transit   2025-06-11            NaN

[729 rows x 4 columns]

In [160]:
data['payments'].isna().sum()

payment_id          0
order_id            0
payment_method      0
payment_status      0
payment_date        0
amount_paid       878
dtype: int64

In [161]:
#2 -  Remove verified exact duplicates from CUSTOMERS

data['customers'].duplicated().sum()

np.int64(50)

In [162]:
duplicated_customers = data['customers'][
    data['customers'].duplicated(subset=["customer_id"], keep=False)
    ].sort_values("customer_id")

In [163]:
duplicated_customers.head(10)

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
348,CUST000349,Grace,Cruz,Female,25.0,grace.cruz@mail.com,9.975817e+09,Region VII,Central Visayas,Lapu-Lapu,Brgy 3,2023-01-25,Gold
5034,CUST000349,Grace,Cruz,Female,25.0,grace.cruz@mail.com,9.975817e+09,Region VII,Central Visayas,Lapu-Lapu,Brgy 3,2023-01-25,Gold
5019,CUST000760,Kyle,Castillo,M,56.0,kyle.castillo26@yahoo.com,9.790834e+09,Region VII,Central Visayas,Lapu-Lapu,Brgy 4,2024-05-31,Gold
759,CUST000760,Kyle,Castillo,M,56.0,kyle.castillo26@yahoo.com,9.790834e+09,Region VII,Central Visayas,Lapu-Lapu,Brgy 4,2024-05-31,Gold
5032,CUST000764,Faith,DelosReyes,F,52.0,faith.delosreyes@yahoo.com,9.399705e+09,CARAGA,Caraga,Bislig,Brgy 5,2023-05-13,Bronze
763,CUST000764,Faith,DelosReyes,F,52.0,faith.delosreyes@yahoo.com,9.399705e+09,CARAGA,Caraga,Bislig,Brgy 5,2023-05-13,Bronze
792,CUST000793,Jasmine,Fernandez,Male,29.0,jasmine.fernandez24@companymail.ph,9.832304e+09,Region VII,Central Visayas,Tagbilaran,Brgy 7,2025-11-10,Bronze
5009,CUST000793,Jasmine,Fernandez,Male,29.0,jasmine.fernandez24@companymail.ph,9.832304e+09,Region VII,Central Visayas,Tagbilaran,Brgy 7,2025-11-10,Bronze
804,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9.755752e+09,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9.755752e+09,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze

In [164]:
customers_clean.duplicated().sum()

np.int64(50)

In [165]:
customers_clean = data['customers'].drop_duplicates().copy()

In [166]:
customers_clean = data['customers'].drop_duplicates()

In [167]:
customers_clean.duplicated().sum()

np.int64(0)

In [168]:
customers_clean[customers_clean['customer_id'] == "CUST000349"]

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
348,CUST000349,Grace,Cruz,Female,25.0,grace.cruz@mail.com,9.975817e+09,Region VII,Central Visayas,Lapu-Lapu,Brgy 3,2023-01-25,Gold

In [169]:
#2 -  Remove verified exact duplicates from ORDERS

data['orders'].duplicated().sum()

np.int64(75)

In [170]:
duplicated_orders = data['orders'][
    data['orders'].duplicated(subset=["order_id"], keep=False)
    ].sort_values("order_id")

In [171]:
duplicated_orders.head(10)

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
15034,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
1082,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15014,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15038,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
1553,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
15027,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
1618,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
15035,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN
1800,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN

In [172]:
orders_clean = data['orders'].copy()

In [173]:
orders_clean.duplicated().sum()

np.int64(75)

In [174]:
orders_clean = data['orders'].drop_duplicates()

In [175]:
orders_clean.duplicated().sum()

np.int64(0)

In [176]:
orders_clean[orders_clean['order_id'] == "ORD0000649"]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68

In [177]:
#2 -  Remove verified exact duplicates from ORDERS ITEMS

data['order_items'].duplicated().sum()

np.int64(262)

In [178]:
data['order_items']

       order_item_id    order_id product_id  quantity unit_price_at_purchase
0      ITEM000000001  ORD0000001  PROD00513         2                 120.67
1      ITEM000000002  ORD0000002  PROD00124         2                  83.58
2      ITEM000000003  ORD0000002  PROD00631         2                  46.96
3      ITEM000000004  ORD0000002  PROD00136         1                 100.59
4      ITEM000000005  ORD0000002  PROD00090         1                 109.18
...              ...         ...        ...       ...                    ...
37758  ITEM000037216  ORD0014888  PROD00095         3                  48.27
37759  ITEM000028576  ORD0011406  PROD00702         1                  46.31
37760  ITEM000026308  ORD0010493  PROD00358         1                 130.84
37761  ITEM000020512  ORD0008174  PROD00075         3                  42.93
37762  ITEM000032925  ORD0013151  PROD00530         1                  106.4

[37763 rows x 5 columns]

In [179]:
duplicated_items = data['order_items'][
    data['order_items'].duplicated(subset=['order_item_id'], keep=False)
    ].sort_values("order_item_id")

In [180]:
duplicated_items.head(10)

       order_item_id    order_id product_id  quantity unit_price_at_purchase
944    ITEM000000945  ORD0000372  PROD00064         2                 ₱90.72
37526  ITEM000000945  ORD0000372  PROD00064         2                 ₱90.72
1163   ITEM000001164  ORD0000458  PROD00166         1                  85.65
37692  ITEM000001164  ORD0000458  PROD00166         1                  85.65
1272   ITEM000001273  ORD0000503  PROD00536         2                  91.52
37695  ITEM000001273  ORD0000503  PROD00536         2                  91.52
1311   ITEM000001312  ORD0000520  PROD00077         4                 135.59
37543  ITEM000001312  ORD0000520  PROD00077         4                 135.59
1353   ITEM000001354  ORD0000534  PROD00505         2                ₱100.11
37550  ITEM000001354  ORD0000534  PROD00505         2                ₱100.11

In [181]:
items_clean = data['order_items'].copy()

In [182]:
items_clean.duplicated().sum()

np.int64(262)

In [183]:
items_clean = data['order_items'].drop_duplicates()

In [184]:
items_clean[items_clean['order_item_id'] == "ITEM000000945"]

     order_item_id    order_id product_id  quantity unit_price_at_purchase
944  ITEM000000945  ORD0000372  PROD00064         2                 ₱90.72

In [185]:
items_clean.duplicated().sum()

np.int64(0)

In [186]:
items_clean['order_item_id'].is_unique

True

In [187]:
#3 - Clean currency fields in products

data['products']

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [188]:
def clean_currency(series):
    return pd.to_numeric(
        series.astype("string")
              .str.replace(
                  "₱", "", regex=False)
              .str.replace(
                  ",", "", regex=False)
              .str.strip(),
        errors="coerce"
    )

In [189]:
products_clean = data['products'].copy()

In [190]:
products_clean['unit_price_num'] = clean_currency(
products_clean['unit_price']
)

In [191]:
products_clean['unit_price_num'].isna().sum()

np.int64(0)

In [192]:
products_clean['unit_price_num']

0        64.5
1       70.39
2       70.26
3       62.46
4       82.02
        ...
795    132.12
796     62.54
797    112.46
798     34.96
799    116.39
Name: unit_price_num, Length: 800, dtype: Float64

In [193]:
products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date,unit_price_num
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18,64.5
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25,70.39
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04,70.26
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12,62.46
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12,82.02
...,...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15,132.12
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05,62.54
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09,112.46
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19,34.96
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022,116.39

In [194]:
#3 - Clean currency fields in ORDER ITEMS

data['order_items']

       order_item_id    order_id product_id  quantity unit_price_at_purchase
0      ITEM000000001  ORD0000001  PROD00513         2                 120.67
1      ITEM000000002  ORD0000002  PROD00124         2                  83.58
2      ITEM000000003  ORD0000002  PROD00631         2                  46.96
3      ITEM000000004  ORD0000002  PROD00136         1                 100.59
4      ITEM000000005  ORD0000002  PROD00090         1                 109.18
...              ...         ...        ...       ...                    ...
37758  ITEM000037216  ORD0014888  PROD00095         3                  48.27
37759  ITEM000028576  ORD0011406  PROD00702         1                  46.31
37760  ITEM000026308  ORD0010493  PROD00358         1                 130.84
37761  ITEM000020512  ORD0008174  PROD00075         3                  42.93
37762  ITEM000032925  ORD0013151  PROD00530         1                  106.4

[37763 rows x 5 columns]

In [195]:
items_clean['unit_price_at_purchase']

0        120.67
1         83.58
2         46.96
3        100.59
4        109.18
          ...
37496     63.45
37497    128.96
37498       NaN
37499    208.44
37500      63.2
Name: unit_price_at_purchase, Length: 37501, dtype: str

In [196]:
items_clean['purchase_price_num'] = clean_currency(
items_clean['unit_price_at_purchase']
)

In [197]:
items_clean['purchase_price_num'].isna().sum()

np.int64(2236)

In [198]:
items_clean['purchase_price_num']

0        120.67
1         83.58
2         46.96
3        100.59
4        109.18
          ...
37496     63.45
37497    128.96
37498      <NA>
37499    208.44
37500      63.2
Name: purchase_price_num, Length: 37501, dtype: Float64

In [199]:
items_clean

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18
...,...,...,...,...,...,...
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45
37497,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96
37498,ITEM000037499,ORD0014999,PROD00689,3,NaN,<NA>
37499,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44
37500,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2

In [200]:
#3 - Clean currency fields in PAYMENTS

data['payments'].dtypes

payment_id        str
order_id          str
payment_method    str
payment_status    str
payment_date      str
amount_paid       str
dtype: object

In [201]:
payments_clean = data['payments'].copy()

In [202]:
payments_clean

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid
0,PAY0000001,ORD0000001,GCash,Paid,2024-05-09,2822.72
1,PAY0000002,ORD0000002,COD,Paid,06/25/2024,2499.76
2,PAY0000003,ORD0000003,GCash,Paid,2025-06-10,1983.66
3,PAY0000004,ORD0000004,PayMaya,Failed,2025-06-21,1765.99
4,PAY0000005,ORD0000005,COD,Pending,06/28/2024,1477.53
...,...,...,...,...,...,...
14995,PAY0014996,ORD0014996,GCash,Paid,2025-06-07,1985.86
14996,PAY0014997,ORD0014997,PayMaya,Paid,2025-12-03,1596.22
14997,PAY0014998,ORD0014998,Bank Transfer,Paid,2026-01-05,836.13
14998,PAY0014999,ORD0014999,GCash,Paid,12/19/2025,NaN
14999,PAY0015000,ORD0015000,GCash,Paid,2025-12-14,2227.32

In [203]:
payments_clean['amount_paid_num'] = clean_currency(
payments_clean['amount_paid']
)

In [204]:
payments_clean['amount_paid_num'].isna().sum()

np.int64(878)

In [205]:
#3 - Clean currency fields in PRODUCTS

data['products'].dtypes

product_id          str
product_name        str
brand               str
category            str
unit_cost       float64
unit_price          str
stock_qty       float64
uom                 str
launch_date         str
dtype: object

In [206]:
products_clean = data['products'].copy()

In [207]:
products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [208]:
products_clean['unit_price_num'] = clean_currency(
products_clean['unit_price']
)

In [209]:
products_clean['unit_price_num'].isna().sum()

np.int64(0)

In [210]:
products_clean.dtypes

product_id            str
product_name          str
brand                 str
category              str
unit_cost         float64
unit_price            str
stock_qty         float64
uom                   str
launch_date           str
unit_price_num    Float64
dtype: object

In [211]:
products_clean.loc[
    products_clean['unit_price_num'].astype('string').str.contains(
        '₱', regex=False, na=False
    ),
    ['unit_price_num']
]

Empty DataFrame
Columns: [unit_price_num]
Index: []

In [212]:
customers_clean.isna().sum()

customer_id       0
first_name        0
last_name         0
gender          298
age             149
email           104
phone           145
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
loyalty_tier    264
dtype: int64

In [213]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST004996,Paolo,Fernandez,Female,18.0,paolo.fernandez57@outlook.com,9.072779e+09,NCR,Metro Manila,Makati,Brgy 6,2025-11-03,Silver
4996,CUST004997,Mia,Flores,M,55.0,miaflores@outlookcom,9.050212e+09,Region III,Central Luzon,Olongapo,Brgy 10,15-Aug-2023,Bronze
4997,CUST004998,Leo,Rivera,Female,17.0,leo.rivera67@yahoo.com,9.517025e+09,NCR,Metro Manila,Makati,Brgy 9,10/12/2023,Bronze
4998,CUST004999,Mark,Fernandez,Female,33.0,mark.fernandez@companymail.ph,9.228372e+09,Region X,Northern Mindanao,Iligan,Brgy 5,2025-06-14,Bronze
4999,CUST005000,Ana,Torres,M,29.0,ana.torres@yahoo.com,9.045344e+09,Region IV-A,CALABARZON,Batangas City,Brgy 4,2023-07-27,Silver

In [214]:
#5 - Normalize customers.gender

customers_clean['gender'].value_counts(dropna=False)

gender
M          1297
F          1263
Female      721
Male        719
Unknown     587
NaN         298
female      115
Name: count, dtype: int64

In [215]:
# M          1297
# F          1263
# Female      721
# Male        719
# Unknown     587
# NaN         298
# female      115

customers_clean["gender_clean"] = (
    customers_clean["gender"]
      .astype("string")
      .str.strip()
      .str.lower()
      .replace({
          "m": "Male",
          "male": "Male",
          "M": "Male",
          "f": "Female",
          "F": "Female",
          "female": "Female",
          "unknown": "Unknown"
      })
      .fillna("Unknown")
)

In [216]:
customers_clean['gender_clean'].value_counts(dropna=False)

gender_clean
Female     2099
Male       2016
Unknown     885
Name: count, dtype: Int64

In [217]:
#4 - Normalize products.category

products_clean['category'].value_counts(dropna=False)

category
Beauty              94
Toys                92
Books               90
Fashion             89
Groceries           77
Home & Kitchen      76
Sports              74
Electronics         71
electronics         20
Book                20
Home and Kitchen    19
Electronics         17
Grocery             12
Elec                11
Beauty & Care       11
Toy                 11
Fashon               8
Sports & Outdoor     8
Name: count, dtype: int64

In [218]:
category_base = (
    products_clean["category"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [219]:
category_map = {
    "electronics": "Electronics",
    "elec": "Electronics",
    "book": "Books",
    "books": "Books",
    "grocery": "Groceries",
    "groceries": "Groceries",
    "home and kitchen": "Home & Kitchen",
    "home & kitchen": "Home & Kitchen",
    "toy": "Toys",
    "toys": "Toys",
    "beauty & care": "Beauty",
    "beauty": "Beauty",
    "fashon": "Fashion",
    "fashion": "Fashion",
    "sports & outdoor": "Sports",
    "sports": "Sports"
}

In [220]:
products_clean['category_clean'] = category_base.replace(category_map)

In [221]:
products_clean['category_clean'].value_counts(dropna=False)

category_clean
Electronics       119
Books             110
Beauty            105
Toys              103
Fashion            97
Home & Kitchen     95
Groceries          89
Sports             82
Name: count, dtype: Int64

In [222]:
products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date,unit_price_num,category_clean
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18,64.5,Beauty
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25,70.39,Home & Kitchen
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04,70.26,Fashion
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12,62.46,Toys
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12,82.02,Books
...,...,...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15,132.12,Electronics
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05,62.54,Books
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09,112.46,Groceries
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19,34.96,Fashion
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022,116.39,Sports

In [223]:
#5 -  parse the mixed date fields - customers

customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN,Female
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST004996,Paolo,Fernandez,Female,18.0,paolo.fernandez57@outlook.com,9.072779e+09,NCR,Metro Manila,Makati,Brgy 6,2025-11-03,Silver,Female
4996,CUST004997,Mia,Flores,M,55.0,miaflores@outlookcom,9.050212e+09,Region III,Central Luzon,Olongapo,Brgy 10,15-Aug-2023,Bronze,Male
4997,CUST004998,Leo,Rivera,Female,17.0,leo.rivera67@yahoo.com,9.517025e+09,NCR,Metro Manila,Makati,Brgy 9,10/12/2023,Bronze,Female
4998,CUST004999,Mark,Fernandez,Female,33.0,mark.fernandez@companymail.ph,9.228372e+09,Region X,Northern Mindanao,Iligan,Brgy 5,2025-06-14,Bronze,Female
4999,CUST005000,Ana,Torres,M,29.0,ana.torres@yahoo.com,9.045344e+09,Region IV-A,CALABARZON,Batangas City,Brgy 4,2023-07-27,Silver,Male

In [224]:
customers_clean['signup_date_clean'] = pd.to_datetime(
    customers_clean['signup_date'],
    format="mixed",
    errors="coerce"
)

In [225]:
customers_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   str
 1   first_name         5000 non-null   str
 2   last_name          5000 non-null   str
 3   gender             4702 non-null   str
 4   age                4851 non-null   float64
 5   email              4896 non-null   str
 6   phone              4855 non-null   float64
 7   region_code        5000 non-null   str
 8   region_name        5000 non-null   str
 9   city               5000 non-null   str
 10  barangay           5000 non-null   str
 11  signup_date        5000 non-null   str
 12  loyalty_tier       4736 non-null   str
 13  gender_clean       5000 non-null   string
 14  signup_date_clean  5000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), str(11), string(1)
memory usage: 586.1 KB

In [226]:
#5 -  parse the mixed date fields - products

products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date,unit_price_num,category_clean
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18,64.5,Beauty
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25,70.39,Home & Kitchen
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04,70.26,Fashion
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12,62.46,Toys
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12,82.02,Books
...,...,...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15,132.12,Electronics
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05,62.54,Books
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09,112.46,Groceries
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19,34.96,Fashion
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022,116.39,Sports

In [227]:
products_clean['launch_date_clean'] = pd.to_datetime(
    products_clean['launch_date'],
    format="mixed",
    errors="coerce"
)

In [228]:
products_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         800 non-null    str
 1   product_name       800 non-null    str
 2   brand              800 non-null    str
 3   category           800 non-null    str
 4   unit_cost          800 non-null    float64
 5   unit_price         800 non-null    str
 6   stock_qty          781 non-null    float64
 7   uom                800 non-null    str
 8   launch_date        800 non-null    str
 9   unit_price_num     800 non-null    Float64
 10  category_clean     800 non-null    string
 11  launch_date_clean  800 non-null    datetime64[us]
dtypes: Float64(1), datetime64[us](1), float64(2), str(7), string(1)
memory usage: 75.9 KB

In [229]:
#5 -  parse the mixed date fields - orders

orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73
...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03

In [230]:
orders_clean['order_datetime_clean'] = pd.to_datetime(
    orders_clean['order_datetime'],
    format="mixed",
    errors="coerce"
)

In [231]:
orders_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              15000 non-null  str
 1   customer_id           15000 non-null  str
 2   order_datetime        15000 non-null  str
 3   order_status          15000 non-null  str
 4   sales_channel         15000 non-null  str
 5   shipping_method       15000 non-null  str
 6   discount_pct          14244 non-null  float64
 7   shipping_fee          14530 non-null  float64
 8   order_datetime_clean  15000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), str(6)
memory usage: 1.0 MB

In [232]:
# 4 - parse the mixed date fields - PAYMENTS

payments_clean

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid,amount_paid_num
0,PAY0000001,ORD0000001,GCash,Paid,2024-05-09,2822.72,2822.72
1,PAY0000002,ORD0000002,COD,Paid,06/25/2024,2499.76,2499.76
2,PAY0000003,ORD0000003,GCash,Paid,2025-06-10,1983.66,1983.66
3,PAY0000004,ORD0000004,PayMaya,Failed,2025-06-21,1765.99,1765.99
4,PAY0000005,ORD0000005,COD,Pending,06/28/2024,1477.53,1477.53
...,...,...,...,...,...,...,...
14995,PAY0014996,ORD0014996,GCash,Paid,2025-06-07,1985.86,1985.86
14996,PAY0014997,ORD0014997,PayMaya,Paid,2025-12-03,1596.22,1596.22
14997,PAY0014998,ORD0014998,Bank Transfer,Paid,2026-01-05,836.13,836.13
14998,PAY0014999,ORD0014999,GCash,Paid,12/19/2025,NaN,<NA>
14999,PAY0015000,ORD0015000,GCash,Paid,2025-12-14,2227.32,2227.32

In [233]:
payments_clean['payment_date_clean'] = pd.to_datetime(
    payments_clean['payment_date'],
    format="mixed",
    errors="coerce"
)

In [234]:
payments_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   payment_id          15000 non-null  str
 1   order_id            15000 non-null  str
 2   payment_method      15000 non-null  str
 3   payment_status      15000 non-null  str
 4   payment_date        15000 non-null  str
 5   amount_paid         14122 non-null  str
 6   amount_paid_num     14122 non-null  Float64
 7   payment_date_clean  15000 non-null  datetime64[us]
dtypes: Float64(1), datetime64[us](1), str(6)
memory usage: 952.3 KB

In [235]:
# 4 - parse the mixed date fields - SHIPMENTS

shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025

In [236]:
shipments_clean['ship_date_clean'] = pd.to_datetime(
    shipments_clean['ship_date'],
    format="mixed",
    errors="coerce"
)

In [237]:
shipments_clean['delivered_date_clean'] = pd.to_datetime(
    shipments_clean['delivered_date'],
    format="mixed",
    errors="coerce"
)

In [238]:
shipments_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   shipment_id           15000 non-null  str
 1   order_id              15000 non-null  str
 2   courier               15000 non-null  str
 3   tracking_no           15000 non-null  str
 4   shipment_status       15000 non-null  str
 5   ship_date             15000 non-null  str
 6   delivered_date        14271 non-null  str
 7   ship_date_clean       15000 non-null  datetime64[us]
 8   delivered_date_clean  14271 non-null  datetime64[us]
dtypes: datetime64[us](2), str(7)
memory usage: 1.0 MB

In [239]:
# 4 - parse the mixed date fields - RETURNS

returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN,True
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False
...,...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74,False
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28,False
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False

In [240]:
returns_clean['return_request_date_clean'] = pd.to_datetime(
    returns_clean['return_request_date'],
    format="mixed",
    errors="coerce"
)

In [241]:
returns_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   return_id                  1200 non-null   str
 1   order_id                   1200 non-null   str
 2   return_request_date        1200 non-null   str
 3   reason                     1200 non-null   str
 4   refunded_flag              1090 non-null   str
 5   refund_amount              1013 non-null   float64
 6   refund_missing             1200 non-null   bool
 7   return_request_date_clean  1200 non-null   datetime64[us]
dtypes: bool(1), datetime64[us](1), float64(1), str(5)
memory usage: 66.9 KB

In [242]:
#5 Flag invalid age

negative_age = customers_clean['age'] < 0

In [243]:
negative_age.sum()

np.int64(48)

In [244]:
customers_clean.loc[negative_age, ["customer_id", "age"]].head(10)

     customer_id  age
162   CUST000163 -1.0
329   CUST000330 -1.0
696   CUST000697 -1.0
718   CUST000719 -1.0
872   CUST000873 -1.0
1194  CUST001195 -1.0
1220  CUST001221 -1.0
1227  CUST001228 -1.0
1303  CUST001304 -1.0
1425  CUST001426 -1.0

In [245]:
under_18 = customers_clean["age"].between(0,17)

In [246]:
under_18.sum()

np.int64(418)

In [247]:
zero_qty = customers_clean["age"] <= 0

In [248]:
zero_qty.sum()

np.int64(49)

In [249]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean,signup_date_clean
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown,2025-12-31
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female,2025-02-08
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male,2023-09-10
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN,Female,2024-11-17
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male,2023-01-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST004996,Paolo,Fernandez,Female,18.0,paolo.fernandez57@outlook.com,9.072779e+09,NCR,Metro Manila,Makati,Brgy 6,2025-11-03,Silver,Female,2025-11-03
4996,CUST004997,Mia,Flores,M,55.0,miaflores@outlookcom,9.050212e+09,Region III,Central Luzon,Olongapo,Brgy 10,15-Aug-2023,Bronze,Male,2023-08-15
4997,CUST004998,Leo,Rivera,Female,17.0,leo.rivera67@yahoo.com,9.517025e+09,NCR,Metro Manila,Makati,Brgy 9,10/12/2023,Bronze,Female,2023-10-12
4998,CUST004999,Mark,Fernandez,Female,33.0,mark.fernandez@companymail.ph,9.228372e+09,Region X,Northern Mindanao,Iligan,Brgy 5,2025-06-14,Bronze,Female,2025-06-14
4999,CUST005000,Ana,Torres,M,29.0,ana.torres@yahoo.com,9.045344e+09,Region IV-A,CALABARZON,Batangas City,Brgy 4,2023-07-27,Silver,Male,2023-07-27

In [250]:
invalid_age = negative_age | under_18 | zero_qty

In [251]:
invalid_age.sum()

np.int64(466)

In [252]:
customers_clean["age_clean"] = customers_clean["age"].copy()

In [253]:
customers_clean.loc[invalid_age, "age_clean"] = np.nan

In [254]:
customers_clean[["customer_id","age","age_clean"]].head(20)

   customer_id   age  age_clean
0   CUST000001  20.0       20.0
1   CUST000002  35.0       35.0
2   CUST000003  14.0        NaN
3   CUST000004  26.0       26.0
4   CUST000005  29.0       29.0
5   CUST000006  31.0       31.0
6   CUST000007  18.0       18.0
7   CUST000008  28.0       28.0
8   CUST000009  36.0       36.0
9   CUST000010  32.0       32.0
10  CUST000011  38.0       38.0
11  CUST000012  33.0       33.0
12  CUST000013  22.0       22.0
13  CUST000014  39.0       39.0
14  CUST000015  23.0       23.0
15  CUST000016  26.0       26.0
16  CUST000017   5.0        NaN
17  CUST000018  35.0       35.0
18  CUST000019  33.0       33.0
19  CUST000020  27.0       27.0

In [255]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean,signup_date_clean,age_clean
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown,2025-12-31,20.0
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female,2025-02-08,35.0
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male,2023-09-10,NaN
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN,Female,2024-11-17,26.0
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male,2023-01-21,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST004996,Paolo,Fernandez,Female,18.0,paolo.fernandez57@outlook.com,9.072779e+09,NCR,Metro Manila,Makati,Brgy 6,2025-11-03,Silver,Female,2025-11-03,18.0
4996,CUST004997,Mia,Flores,M,55.0,miaflores@outlookcom,9.050212e+09,Region III,Central Luzon,Olongapo,Brgy 10,15-Aug-2023,Bronze,Male,2023-08-15,55.0
4997,CUST004998,Leo,Rivera,Female,17.0,leo.rivera67@yahoo.com,9.517025e+09,NCR,Metro Manila,Makati,Brgy 9,10/12/2023,Bronze,Female,2023-10-12,NaN
4998,CUST004999,Mark,Fernandez,Female,33.0,mark.fernandez@companymail.ph,9.228372e+09,Region X,Northern Mindanao,Iligan,Brgy 5,2025-06-14,Bronze,Female,2025-06-14,33.0
4999,CUST005000,Ana,Torres,M,29.0,ana.torres@yahoo.com,9.045344e+09,Region IV-A,CALABARZON,Batangas City,Brgy 4,2023-07-27,Silver,Male,2023-07-27,29.0

In [256]:
#5 Flag invalid - order_items.zero quantity

zero_qty  = items_clean['quantity'] <= 0

In [257]:
zero_qty.sum()

np.int64(372)

In [258]:
items_clean

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18
...,...,...,...,...,...,...
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45
37497,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96
37498,ITEM000037499,ORD0014999,PROD00689,3,NaN,<NA>
37499,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44
37500,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2

In [259]:
invalid_qty = zero_qty

In [260]:
items_clean["quantity_clean"] = items_clean["quantity"].copy()

In [261]:
items_clean.loc[invalid_qty, "quantity_clean"] = np.nan

In [262]:
items_clean.loc[
    items_clean["quantity"] == 0,
    ["order_item_id", "quantity", "quantity_clean"]
]

       order_item_id  quantity  quantity_clean
44     ITEM000000045         0             NaN
186    ITEM000000187         0             NaN
247    ITEM000000248         0             NaN
376    ITEM000000377         0             NaN
397    ITEM000000398         0             NaN
...              ...       ...             ...
36919  ITEM000036920         0             NaN
37127  ITEM000037128         0             NaN
37201  ITEM000037202         0             NaN
37434  ITEM000037435         0             NaN
37436  ITEM000037437         0             NaN

[372 rows x 3 columns]

In [263]:
#5 Flag invalid - returns.inconsistent refund records

returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing,return_request_date_clean
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True,2025-01-09
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False,2025-07-20
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN,True,2025-01-07
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True,2025-03-04
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False,2025-04-24
...,...,...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False,2024-11-02
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74,False,2024-10-10
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False,2025-06-25
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28,False,2024-02-20
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False,2025-08-12

In [264]:
refund_yes_no_amount = (
    returns_clean["refunded_flag"].eq("Yes")
    & returns_clean["refund_amount"].isna()
)

refund_no_has_amount = (
    returns_clean["refunded_flag"].eq("No")
    & returns_clean["refund_amount"].notna()
)

In [265]:
refund_yes_no_amount

0       False
1       False
2        True
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Length: 1200, dtype: bool

In [266]:
refund_no_has_amount

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196     True
1197    False
1198     True
1199    False
Length: 1200, dtype: bool

In [267]:
inconsistent_refund = (
    refund_yes_no_amount
    | refund_no_has_amount
)

returns_clean["refund_inconsistent"] = inconsistent_refund

# This creates a new Boolean column named refund_inconsistent:
# - True — the record violates at least one of the two rules.
# - False — neither of the two rules was violated

In [268]:
returns_clean.loc[
    returns_clean["refund_inconsistent"],
    [
        "return_id",
        "order_id",
        "refunded_flag",
        "refund_amount",
        "refund_inconsistent"
    ]
]

      return_id    order_id refunded_flag  refund_amount  refund_inconsistent
2     RET000003  ORD0009041           Yes            NaN                 True
6     RET000007  ORD0009572            No         931.12                 True
8     RET000009  ORD0007574           Yes            NaN                 True
9     RET000010  ORD0003302            No        1048.55                 True
13    RET000014  ORD0006890           Yes            NaN                 True
...         ...         ...           ...            ...                  ...
1183  RET001184  ORD0000710           Yes            NaN                 True
1185  RET001186  ORD0011823            No         761.12                 True
1193  RET001194  ORD0007425            No         560.99                 True
1196  RET001197  ORD0011974            No         356.74                 True
1198  RET001199  ORD0011487            No         171.28                 True

[347 rows x 5 columns]

In [269]:
returns_clean["refund_inconsistent"].sum()

np.int64(347)

In [270]:
returns_clean.loc[
    returns_clean["refund_inconsistent"] == False
]

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing,return_request_date_clean,refund_inconsistent
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True,2025-01-09,False
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False,2025-07-20,False
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True,2025-03-04,False
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False,2025-04-24,False
5,RET000006,ORD0002714,2024-07-05,Size issue,Partial,675.23,False,2024-07-05,False
...,...,...,...,...,...,...,...,...,...
1192,RET001193,ORD0008027,2024-03-03,Size issue,Partial,301.48,False,2024-03-03,False
1194,RET001195,ORD0012656,2024-03-06,Late delivery,Yes,61.29,False,2024-03-06,False
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False,2024-11-02,False
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False,2025-06-25,False
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False,2025-08-12,False

In [317]:
#5 Orphan Customers

missing_customers = (
    set(orders_clean["customer_id"]) - set(customers_clean["customer_id"])
)

In [318]:
missing_customers

{'CUST999999'}

In [320]:
orders_clean.loc[
    orders_clean["customer_id"].isin(missing_customers)
]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean
602,ORD0000603,CUST999999,01/02/2024 09:07 PM,Shipped,Web,Express,0.101,100.45,2024-01-02 21:07:00
756,ORD0000757,CUST999999,2025-05-19 14:53:00,Completed,Web,Standard,0.005,71.00,2025-05-19 14:53:00
806,ORD0000807,CUST999999,2024-04-06 03:40:00,Completed,Web,Standard,0.194,94.34,2024-04-06 03:40:00
1478,ORD0001479,CUST999999,2024-04-02 23:15:00,Completed,Mobile App,Express,0.161,107.78,2024-04-02 23:15:00
1855,ORD0001856,CUST999999,2024-08-08 01:40:00,Completed,Mobile App,Express,0.080,101.14,2024-08-08 01:40:00
2770,ORD0002771,CUST999999,2025-01-28 12:40:00,Completed,Mobile App,Pickup,0.091,100.96,2025-01-28 12:40:00
2919,ORD0002920,CUST999999,2024-10-21 09:50:00,Completed,Marketplace,Pickup,0.067,74.64,2024-10-21 09:50:00
3569,ORD0003570,CUST999999,06/05/2024 09:24 AM,Cancelled,Web,Express,0.029,104.07,2024-06-05 09:24:00
3760,ORD0003761,CUST999999,2025-11-20 20:33:00,Returned,Marketplace,Pickup,0.000,94.26,2025-11-20 20:33:00
4881,ORD0004882,CUST999999,2025-05-16 16:56:00,Completed,Mobile App,Express,0.000,64.93,2025-05-16 16:56:00
4887,ORD0004888,CUST999999,10/15/2025 07:31 AM,Completed,Web,Pickup,0.000,122.26,2025-10-15 07:31:00
4891,ORD0004892,CUST999999,2024-05-07 17:14:00,Pending,Mobile App,Express,0.114,62.66,2024-05-07 17:14:00
5064,ORD0005065,CUST999999,2026-01-17 05:27:00,Completed,Marketplace,Pickup,0.000,85.11,2026-01-17 05:27:00
5128,ORD0005129,CUST999999,03/29/2024 12:39 PM,Completed,Mobile App,Standard,NaN,37.05,2024-03-29 12:39:00
5292,ORD0005293,CUST999999,2025-10-16 20:56:00,Completed,Marketplace,Pickup,0.302,49.99,2025-10-16 20:56:00
5402,ORD0005403,CUST999999,2024-06-25 12:32:00,Completed,Mobile App,Standard,0.000,151.33,2024-06-25 12:32:00
5674,ORD0005675,CUST999999,09/09/2025 10:48 PM,Completed,Marketplace,Pickup,NaN,70.47,2025-09-09 22:48:00
5898,ORD0005899,CUST999999,2026-01-01 10:01:00,Cancelled,Marketplace,Express,0.140,5.59,2026-01-01 10:01:00
6121,ORD0006122,CUST999999,03/03/2024 10:54 PM,Pending,Marketplace,Standard,0.080,111.26,2024-03-03 22:54:00
6125,ORD0006126,CUST999999,2024-08-05 03:11:00,Completed,Mobile App,Standard,0.000,92.05,2024-08-05 03:11:00
6272,ORD0006273,CUST999999,2025-06-03 19:59:00,Completed,Web,Standard,0.046,57.76,2025-06-03 19:59:00
6833,ORD0006834,CUST999999,2024-05-17 20:59:00,Completed,Marketplace,Pickup,0.075,61.71,2024-05-17 20:59:00
6886,ORD0006887,CUST999999,2025-02-23 19:26:00,Completed,Mobile App,Standard,0.039,59.69,2025-02-23 19:26:00
7295,ORD0007296,CUST999999,2024-05-31 16:42:00,Pending,Web,Standard,0.156,37.85,2024-05-31 16:42:00
7720,ORD0007721,CUST999999,06/05/2025 07:16 AM,Completed,Web,Pickup,0.089,95.38,2025-06-05 07:16:00
7721,ORD0007722,CUST999999,2024-03-06 14:18:00,Completed,Web,Standard,0.071,134.71,2024-03-06 14:18:00
8155,ORD0008156,CUST999999,2025-08-18 08:45:00,Completed,Web,Pickup,0.180,11.76,2025-08-18 08:45:00
8237,ORD0008238,CUST999999,07/12/2024 09:03 PM,Completed,Mobile App,Standard,0.014,61.38,2024-07-12 21:03:00
8313,ORD0008314,CUST999999,2024-07-21 18:26:00,Completed,Marketplace,Express,0.105,88.69,2024-07-21 18:26:00
8580,ORD0008581,CUST999999,11/12/2025 12:34 AM,Completed,Mobile App,Standard,0.000,87.17,2025-11-12 00:34:00
9338,ORD0009339,CUST999999,03/12/2024 02:23 PM,Cancelled,Mobile App,Pickup,0.076,70.38,2024-03-12 14:23:00
9533,ORD0009534,CUST999999,16-Apr-2024 22:51,Completed,Marketplace,Pickup,0.000,99.03,2024-04-16 22:51:00
10284,ORD0010285,CUST999999,27-Feb-2025 02:46,Cancelled,Web,Standard,0.074,165.93,2025-02-27 02:46:00
10365,ORD0010366,CUST999999,2024-05-05 02:10:00,Completed,Mobile App,Pickup,0.229,93.97,2024-05-05 02:10:00
10457,ORD0010458,CUST999999,2024-06-29 10:36:00,Completed,Marketplace,Standard,0.000,112.26,2024-06-29 10:36:00
10675,ORD0010676,CUST999999,2025-02-28 12:31:00,Pending,Web,Express,0.076,89.33,2025-02-28 12:31:00
10791,ORD0010792,CUST999999,2024-04-11 16:04:00,Completed,Marketplace,Express,0.169,59.91,2024-04-11 16:04:00
11224,ORD0011225,CUST999999,04/24/2024 04:52 PM,Completed,Mobile App,Express,NaN,120.16,2024-04-24 16:52:00
12257,ORD0012258,CUST999999,2024-07-09 18:38:00,Completed,Mobile App,Express,0.066,116.58,2024-07-09 18:38:00
12901,ORD0012902,CUST999999,2024-01-27 17:20:00,Completed,Web,Express,0.054,106.20,2024-01-27 17:20:00
13188,ORD0013189,CUST999999,26-Jan-2026 08:37,Returned,Marketplace,Express,0.162,88.99,2026-01-26 08:37:00
14196,ORD0014197,CUST999999,09-Jan-2024 16:47,Completed,Mobile App,Express,0.127,40.38,2024-01-09 16:47:00
14450,ORD0014451,CUST999999,01/05/2025 08:55 AM,Completed,Marketplace,Express,0.003,2.08,2025-01-05 08:55:00

In [345]:
audit_missing_customers = orders_clean.merge(
customers_clean[["customer_id", "first_name", "last_name"]],
on="customer_id",
how="left",
indicator=True
)

In [346]:
audit_missing_customers

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,missing_customer,first_name,last_name,_merge
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,False,Jose,Reyes,both
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,False,Noah,Bautista,both
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,False,Leo,Villanueva,both
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,False,Faith,Cruz,both
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,False,Leo,Pascual,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,False,Maria,Pascual,both
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,False,Mia,Lopez,both
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,False,Jose,Fernandez,both
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,False,Kyle,Santos,both
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,False,Carlo,Santos,both

In [347]:
audit_missing_customers["_merge"].value_counts()

_merge
both          14957
left_only        43
right_only        0
Name: count, dtype: int64

In [356]:
#FLAGGED missing customers

orders_clean["missing_customers"] = ~orders_clean["customer_id"].isin(
    customers_clean["customer_id"]
)

In [357]:
#Display the flagged orders

orders_clean.loc[
    orders_clean["missing_customers"],
    ["order_id", "customer_id", "missing_customers"]
]

         order_id customer_id  missing_customers
602    ORD0000603  CUST999999               True
756    ORD0000757  CUST999999               True
806    ORD0000807  CUST999999               True
1478   ORD0001479  CUST999999               True
1855   ORD0001856  CUST999999               True
2770   ORD0002771  CUST999999               True
2919   ORD0002920  CUST999999               True
3569   ORD0003570  CUST999999               True
3760   ORD0003761  CUST999999               True
4881   ORD0004882  CUST999999               True
4887   ORD0004888  CUST999999               True
4891   ORD0004892  CUST999999               True
5064   ORD0005065  CUST999999               True
5128   ORD0005129  CUST999999               True
5292   ORD0005293  CUST999999               True
5402   ORD0005403  CUST999999               True
5674   ORD0005675  CUST999999               True
5898   ORD0005899  CUST999999               True
6121   ORD0006122  CUST999999               True
6125   ORD0006126  CUST999999               True
6272   ORD0006273  CUST999999               True
6833   ORD0006834  CUST999999               True
6886   ORD0006887  CUST999999               True
7295   ORD0007296  CUST999999               True
7720   ORD0007721  CUST999999               True
7721   ORD0007722  CUST999999               True
8155   ORD0008156  CUST999999               True
8237   ORD0008238  CUST999999               True
8313   ORD0008314  CUST999999               True
8580   ORD0008581  CUST999999               True
9338   ORD0009339  CUST999999               True
9533   ORD0009534  CUST999999               True
10284  ORD0010285  CUST999999               True
10365  ORD0010366  CUST999999               True
10457  ORD0010458  CUST999999               True
10675  ORD0010676  CUST999999               True
10791  ORD0010792  CUST999999               True
11224  ORD0011225  CUST999999               True
12257  ORD0012258  CUST999999               True
12901  ORD0012902  CUST999999               True
13188  ORD0013189  CUST999999               True
14196  ORD0014197  CUST999999               True
14450  ORD0014451  CUST999999               True

In [358]:
#Count the missing customers records

orders_clean["missing_customers"].sum()

np.int64(43)

In [359]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,missing_customer,missing_customers
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,False,False
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,False,False
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,False,False
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,False,False
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,False,False
...,...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,False,False
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,False,False
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,False,False
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,False,False
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,False,False

In [295]:
#5 Orphan Products

missing_products = (
set(items_clean["product_id"])- set(products_clean["product_id"])
)

In [296]:
missing_products

{'PROD00000'}

In [340]:
items_clean.loc[
    items_clean["product_id"].isin(missing_products)
]

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,quantity_clean
377,ITEM000000378,ORD0000148,PROD00000,1,106.4,106.4,1.0
601,ITEM000000602,ORD0000241,PROD00000,1,54.41,54.41,1.0
692,ITEM000000693,ORD0000275,PROD00000,2,135.29,135.29,2.0
935,ITEM000000936,ORD0000370,PROD00000,1,30.34,30.34,1.0
1108,ITEM000001109,ORD0000435,PROD00000,1,95.17,95.17,1.0
...,...,...,...,...,...,...,...
37231,ITEM000037232,ORD0014893,PROD00000,3,161.46,161.46,3.0
37339,ITEM000037340,ORD0014935,PROD00000,6,188.5,188.5,6.0
37373,ITEM000037374,ORD0014952,PROD00000,1,137.74,137.74,1.0
37464,ITEM000037465,ORD0014986,PROD00000,4,58.28,58.28,4.0
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,1.0

In [348]:
audit_missing_products = items_clean.merge(
    data["products"][["product_id", "product_name"]],
    on="product_id",
    how="left",
    indicator=True
)

In [349]:
audit_missing_products

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,quantity_clean,product_name,_merge
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,2.0,HomeEase Sports 313,both
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,2.0,NovaTech Beauty 892,both
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,2.0,BookNest Electronics 252,both
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,1.0,GlowCo Groceries 689,both
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,1.0,BookNest Home 591,both
...,...,...,...,...,...,...,...,...,...
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,1.0,NaN,left_only
37497,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,1.0,KidJoy Toys 976,both
37498,ITEM000037499,ORD0014999,PROD00689,3,NaN,<NA>,3.0,FreshCart Sports 375,both
37499,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,2.0,KidJoy Beauty 728,both
37500,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,2.0,HomeEase Electronics 592,both

In [350]:
audit_missing_products["_merge"].value_counts()

_merge
both          37372
left_only       129
right_only        0
Name: count, dtype: int64

In [352]:
#FLAGGED missing products

items_clean["missing_products"] = ~items_clean["product_id"].isin(
    products_clean["product_id"]
)

In [353]:
#Display the flagged orders

items_clean.loc[
    items_clean["missing_products"],
    ["order_item_id", "product_id", "missing_products"]
]

       order_item_id product_id  missing_products
377    ITEM000000378  PROD00000              True
601    ITEM000000602  PROD00000              True
692    ITEM000000693  PROD00000              True
935    ITEM000000936  PROD00000              True
1108   ITEM000001109  PROD00000              True
...              ...        ...               ...
37231  ITEM000037232  PROD00000              True
37339  ITEM000037340  PROD00000              True
37373  ITEM000037374  PROD00000              True
37464  ITEM000037465  PROD00000              True
37496  ITEM000037497  PROD00000              True

[129 rows x 3 columns]

In [354]:
#Count the missing products records

items_clean["missing_products"].sum()

np.int64(129)

In [381]:
#6 #Build Analysis-Ready Fields from Cleaned Tables

items_analysis = items_clean.copy()

items_analysis["purchase_price_num"] = (
    clean_currency(
        items_analysis["unit_price_at_purchase"]
    )
)

items_analysis = items_analysis[
    (items_analysis["quantity"] > 0)
    & items_analysis["purchase_price_num"].notna()
]

items_analysis = items_analysis.merge(
    products_clean[["product_id", "unit_cost", "category_clean"]],
    on="product_id",
    how="left"
)

items_analysis = items_analysis.merge(
    orders_clean[["order_id", "sales_channel"]],
    on="order_id",
    how="left"
)

items_analysis["line_revenue"] = (
    items_analysis["quantity"]
    * items_analysis["purchase_price_num"]
)

items_analysis["line_cost"] = (
    items_analysis["quantity"]
    * items_analysis["unit_cost"]
)

items_analysis["line_profit"] = (
    items_analysis["line_revenue"]
    - items_analysis["line_cost"]
)

In [382]:
items_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,quantity_clean,missing_products,unit_cost,category_clean,sales_channel,line_revenue,line_cost,line_profit
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,2.0,False,71.15,Sports,Marketplace,241.34,142.30,99.04
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,2.0,False,63.11,Beauty,Marketplace,167.16,126.22,40.94
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,2.0,False,30.08,Electronics,Marketplace,93.92,60.16,33.76
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,1.0,False,55.82,Groceries,Marketplace,100.59,55.82,44.77
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,1.0,False,74.36,Home & Kitchen,Marketplace,109.18,74.36,34.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,1.0,False,56.45,Home & Kitchen,Web,69.64,56.45,13.19
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,1.0,True,NaN,<NA>,Web,63.45,NaN,<NA>
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,1.0,False,96.76,Toys,Web,128.96,96.76,32.2
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,2.0,False,124.37,Beauty,Marketplace,416.88,248.74,168.14
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,2.0,False,40.73,Electronics,Marketplace,126.4,81.46,44.94

In [384]:
#Compare Sales Channels with groupby()

sales_analysis = items_analysis.merge(
    orders_clean[["order_id", "order_status"]],
    on="order_id",
    how="left"
)

channel_summary = (
    sales_analysis
    .groupby("sales_channel")
    .agg(
        gross_line_revenue=("line_revenue", "sum"),
        average_line_revenue=("line_revenue", "mean"),
        line_items=("order_item_id", "count"),
        orders=("order_id", "nunique")
    )
    .sort_values(
        "gross_line_revenue", ascending=False
    )
)

print(channel_summary)

               gross_line_revenue  average_line_revenue  line_items  orders
sales_channel
Web                    2324877.34            199.972247       11626    4885
Marketplace            2312808.93            198.337101       11661    4961
Mobile App             2290206.85            197.007041       11625    4912

In [386]:
#EDA 1 - Which sales channel contributes most gross item revenue?

channel_summary = (
    items_analysis
    .groupby("sales_channel")
    .agg(
        gross_line_revenue=("line_revenue", "sum"),
        orders=("order_id", "nunique")
    )
    .sort_values("gross_line_revenue", ascending=False)
)

print(channel_summary)

               gross_line_revenue  orders
sales_channel
Web                    2324877.34    4885
Marketplace            2312808.93    4961
Mobile App             2290206.85    4912

EDA#1 findings: The Web sales channel contributes the most gross item revenue, totaling 2,324,877.34 across 4,885 unique orders. However, gross revenue alone does not indicate which channel is the most profitable.

In [387]:
#EDA 2 - Which cleaned product category has highest item revenue?


category_summary = (
    items_analysis
    .groupby("category_clean")
    .agg(
        gross_line_revenue=("line_revenue", "sum"),
        line_items=("order_item_id", "count")
    )
    .sort_values(
        "gross_line_revenue", ascending=False
    )
)

print(category_summary)

                gross_line_revenue  line_items
category_clean
Toys                     964419.21        4562
Electronics               940990.3        5045
Fashion                  888891.75        4248
Beauty                   882258.05        4558
Home & Kitchen            875264.9        4247
Books                    811802.93        4707
Groceries                790644.27        3862
Sports                   747455.58        3565

EDA#2 findings: Toys generated the highest gross line revenue among the product categories, exceeding Electronics by ₱23,428.91. Electronics had the most line items, with 5,045, showing that the category with the most line items is not necessarily the one with the highest revenue.

In [391]:
#EDA 3 - Which payment method is most common?

payments_clean["payment_method"].value_counts().reset_index()

  payment_method  count
0    Credit Card   3137
1        PayMaya   3035
2            COD   3030
3          GCash   2925
4  Bank Transfer   2873

EDA#3 findings: Credit Card was the most frequently recorded payment method, with 3,137 records. This measures usage frequency, not the total amount paid through each method.

In [393]:
#EDA 4 - What return reason occurs most often?

returns_clean["reason"].value_counts().reset_index()

          reason  count
0   Changed mind    182
1      Defective    178
2  Missing parts    175
3     Size issue    174
4  Late delivery    169
5     Wrong item    162
6   Damaged item    160

EDA#4 findings: Changed mind was the most frequently recorded return reason, appearing in 182 return records. However, return frequency alone does not indicate which reason has the greatest financial loss or operational impact. Further analysis of refund amounts and returned product values is needed to determine the financial impact of each return reason.

In [398]:
#EDA 5 - Which courier handles the most shipments?

shipments_clean["courier"].value_counts()

courier
J&T            3042
GrabExpress    3011
LBC            3011
NinjaVan       2985
2GO            2951
Name: count, dtype: int64

EDA#5 findings: J&T handled the highest shipment volume, with 3,042 shipments. However, a higher shipment volume does not necessarily indicate better delivery quality; on-time delivery rates, delays, and failed deliveries should also be evaluated.

In [ ]:

# ============================================================
# DATA CLEANING DECISIONS DOCUMENTATION
# ============================================================

# 1. REMOVING DUPLICATE RECORDS
# What changed:
# Removed exact duplicate rows from the original tables
# to create cleaned DataFrames using drop_duplicates().
#
# Why:
# Duplicate records can inflate record counts and distort
# sales and customer analysis.
#
# How it was verified:
# Counted duplicate rows before and after cleaning.

print("1. Duplicate Records")
print("Before cleaning:", data["order_items"].duplicated().sum())
print("After cleaning:", items_clean.duplicated().sum())


# 2. FLAGGING INVALID CUSTOMER AGES
# What changed:
# Flagged customer records with negative ages, ages below 18,
# or other invalid values based on the defined business rules.
#
# Why:
# Invalid ages may affect customer segmentation and analysis.
#
# How it was verified:
# Counted and inspected records that violated the rules.

print("\n2. Invalid Customer Ages")
print("Negative ages:", negative_age.sum())
print("Under 18:", under_18.sum())
print("Zero quantities:", zero_qty.sum())


# 3. FLAGGING INVALID ORDER QUANTITIES
# What changed:
# Identified order items with zero or negative quantities.
#
# Why:
# Invalid quantities can distort revenue and cost calculations.
#
# How it was verified:
# Counted invalid quantities and inspected affected records.

print("\n3. Invalid Order Quantities")
print("Invalid quantity records:", (items_clean["quantity"] <= 0).sum())


# 4. CLEANING CURRENCY VALUES
# What changed:
# Converted purchase price values into numeric format using
# the clean_currency() function.
#
# Why:
# Currency symbols and inconsistent formats may prevent
# accurate mathematical calculations.
#
# How it was verified:
# Inspected the converted values and checked their data type.

print("\n4. Currency Cleaning")
print(items_analysis["purchase_price_num"].dtype)
print("Missing numeric prices:",
      items_analysis["purchase_price_num"].isna().sum())


# 5. FLAGGING INCONSISTENT REFUND RECORDS
# What changed:
# Flagged records where refunded_flag and refund_amount
# do not agree.
#
# Why:
# Conflicting refund information may affect refund reporting
# and financial analysis.
#
# How it was verified:
# Counted and inspected records with conflicting combinations.

print("\n5. Inconsistent Refund Records")
print("Yes but missing amount:", refund_yes_no_amount.sum())
print("No but has amount:", refund_no_has_amount.sum())


# 6. CHECKING MISSING CUSTOMER REFERENCES
# What changed:
# Identified orders whose customer IDs do not exist
# in the cleaned customers table.
#
# Why:
# Missing customer matches can affect customer-level analysis.
#
# How it was verified:
# Counted the unmatched customer IDs and inspected the orders.

print("\n6. Orphan Customer IDs")
print("Orders with unmatched customers:", missing_customer.sum())


# 7. CHECKING MISSING PRODUCT REFERENCES
# What changed:
# Identified order items whose product IDs do not match
# records in the products table.
#
# Why:
# Missing product matches can affect product category,
# cost, and profitability analysis.
#
# How it was verified:
# Used a left merge with an indicator to identify unmatched rows.

print("\n7. Orphan Product IDs")
print(audit["_merge"].value_counts())

In [406]:
tables = {
    "customers_clean": customers_clean,
    "orders_clean": orders_clean,
    "items_clean": items_clean,
    "payments_clean": payments_clean,
    "returns_clean": returns_clean,
    "products_clean": products_clean,
    "shipments_clean": shipments_clean
}

for name, df in tables.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

customers_clean: 0 duplicate rows
orders_clean: 0 duplicate rows
items_clean: 0 duplicate rows
payments_clean: 0 duplicate rows
returns_clean: 0 duplicate rows
products_clean: 0 duplicate rows
shipments_clean: 0 duplicate rows

In [415]:
tables = {
    "customers_clean": customers_clean,
    "orders_clean": orders_clean,
    "items_clean": items_clean,
    "payments_clean": payments_clean,
    "returns_clean": returns_clean,
    "products_clean": products_clean,
    "shipments_clean": shipments_clean
}

for name, df in tables.items():
    print(f"\n{name}")
    print(df.isna().sum())

customers_clean
customer_id            0
first_name             0
last_name              0
gender                 0
age                    0
email                  0
phone                  0
region_code            0
region_name            0
city                   0
barangay               0
signup_date            0
loyalty_tier           0
gender_clean           0
signup_date_clean      0
age_clean            615
dtype: int64

orders_clean
order_id                  0
customer_id               0
order_datetime            0
order_status              0
sales_channel             0
shipping_method           0
discount_pct            756
shipping_fee            470
order_datetime_clean      0
missing_customers         0
dtype: int64

items_clean
order_item_id                0
order_id                     0
product_id                   0
quantity                     0
unit_price_at_purchase    2236
purchase_price_num        2236
quantity_clean             372
missing_products             0
dtype: int64

payments_clean
payment_id              0
order_id                0
payment_method          0
payment_status          0
payment_date            0
amount_paid           878
amount_paid_num       878
payment_date_clean      0
dtype: int64

returns_clean
return_id                      0
order_id                       0
return_request_date            0
reason                         0
refunded_flag                110
refund_amount                187
refund_missing                 0
return_request_date_clean      0
refund_inconsistent            0
dtype: int64

products_clean
product_id            0
product_name          0
brand                 0
category              0
unit_cost             0
unit_price            0
stock_qty            19
uom                   0
launch_date           0
unit_price_num        0
category_clean        0
launch_date_clean     0
dtype: int64

shipments_clean
shipment_id               0
order_id                  0
courier                   0
tracking_no               0
shipment_status           0
ship_date                 0
delivered_date          729
ship_date_clean           0
delivered_date_clean    729
dtype: int64

In [416]:
customers_clean.to_csv("customers_clean.csv", index=False)
orders_clean.to_csv("orders_clean.csv", index=False)
items_clean.to_csv("items_clean.csv", index=False)
products_clean.to_csv("products_clean.csv", index=False)
payments_clean.to_csv("payments_clean.csv", index=False)
returns_clean.to_csv("returns_clean.csv", index=False)
shipments_clean.to_csv("shipments_clean.csv", index=False)